// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/shortener.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CustomAlias   string                 `protobuf:"bytes,2,opt,name=custom_alias,json=customAlias,proto3" json:"custom_alias,omitempty"`
	ExpireInDays  int32                  `protobuf:"varint,3,opt,name=expire_in_days,json=expireInDays,proto3" json:"expire_in_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenerRequest) Reset() {
	*x = ShortenerRequest{}
	mi := &file_api_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerRequest) ProtoMessage() {}

func (x *ShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerRequest.ProtoReflect.Descriptor instead.
func (*ShortenerRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenerRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenerRequest) GetCustomAlias() string {
	if x != nil {
		return x.CustomAlias
	}
	return ""
}

func (x *ShortenerRequest) GetExpireInDays() int32 {
	if x != nil {
		return x.ExpireInDays
	}
	return 0
}

type ShortenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenerResponse) Reset() {
	*x = ShortenerResponse{}
	mi := &file_api_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerResponse) ProtoMessage() {}

func (x *ShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerResponse.ProtoReflect.Descriptor instead.
func (*ShortenerResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenerResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_api_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *RedirectRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_api_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *RedirectResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_api_shortener_proto protoreflect.FileDescriptor

const file_api_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13api/shortener.proto\x12\tshortener\x1a\x1cgoogle/api/annotations.proto\"v\n" +
	"\x10ShortenerRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12!\n" +
	"\fcustom_alias\x18\x02 \x01(\tR\vcustomAlias\x12$\n" +
	"\x0eexpire_in_days\x18\x03 \x01(\x05R\fexpireInDays\"0\n" +
	"\x11ShortenerResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\".\n" +
	"\x0fRedirectRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"-\n" +
	"\x10RedirectResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl2\xd9\x01\n" +
	"\x10ShortenerService\x12a\n" +
	"\x0fCreateShortener\x12\x1b.shortener.ShortenerRequest\x1a\x1c.shortener.ShortenerResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/shorten\x12b\n" +
	"\x11RedirectShortener\x12\x1a.shortener.RedirectRequest\x1a\x1b.shortener.RedirectResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/{short_url}B\x16Z\x14urlshortener/api;apib\x06proto3"

var (
	file_api_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_proto_rawDescData []byte
)

func file_api_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)))
	})
	return file_api_shortener_proto_rawDescData
}

var file_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_shortener_proto_goTypes = []any{
	(*ShortenerRequest)(nil),  // 0: shortener.ShortenerRequest
	(*ShortenerResponse)(nil), // 1: shortener.ShortenerResponse
	(*RedirectRequest)(nil),   // 2: shortener.RedirectRequest
	(*RedirectResponse)(nil),  // 3: shortener.RedirectResponse
}
var file_api_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.ShortenerService.CreateShortener:input_type -> shortener.ShortenerRequest
	2, // 1: shortener.ShortenerService.RedirectShortener:input_type -> shortener.RedirectRequest
	1, // 2: shortener.ShortenerService.CreateShortener:output_type -> shortener.ShortenerResponse
	3, // 3: shortener.ShortenerService.RedirectShortener:output_type -> shortener.RedirectResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_shortener_proto_init() }
func file_api_shortener_proto_init() {
	if File_api_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_proto = out.File
	file_api_shortener_proto_goTypes = nil
	file_api_shortener_proto_depIdxs = nil
}
